name: Create and Publish Archive
on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases and upload assets
    steps:
    - uses: actions/checkout@master
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    
    - name: Set Version
      id: version
      run: |
        # Read the base version from version.txt
        BASE_VERSION=$(cat version.txt)
        RUN_NUMBER=${{ github.run_number }}
        TAG_NAME="${BASE_VERSION}_alpha${RUN_NUMBER}"
        echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
        echo "release_name=Release ${TAG_NAME}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN
      with:
        tag_name: ${{ steps.version.outputs.tag_name }}
        release_name: ${{ steps.version.outputs.release_name }}
        draft: false
        prerelease: false
    
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: release.zip
        tag_name: ${{ steps.version.outputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN
