name: Zip Addons Folder

on:
  push:
    branches:
      - main

jobs:
  zip-addons:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Zip addons folder
        run: zip -r addons.zip addons/
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: addons-zip
          path: addons.zip
